version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: my_postgres_db
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_USER: postgres
      POSTGRES_DB: crud-prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
