version: '3.8'

services:
  db:
    image: postgres
    container_name: my_postgres_db
    environment:
      POSTGRES_PASSWORD: root123
      POSTGRES_USER: postgres
      POSTGRES_DB: crud-prisma
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: